// Sample data for recipes
const recipes = {
    'Adobong Manok (Chicken Adobo)': {
        ingredients: [
            '1 kg (2.2 lbs) chicken (cut into serving pieces, such as thighs, drumsticks, or a whole chicken chopped up)',
            '1/2 cup soy sauce',
            '1/4 cup vinegar',
            '1 medium onion (chopped)',
            '5-6 cloves garlic (minced)',
            '2-3 bay leaves',
            '1 teaspoon whole black peppercorns',
            '1/2 teaspoon ground black pepper',
            '1 tablespoon brown sugar (optional)',
            '2 tablespoons cooking oil',
            '1 cup water or chicken broth',
            '2-3 medium potatoes (peeled and quartered, optional)',
            '1-2 hard-boiled eggs (optional)',
            'Salt to taste',
            'Green onions or parsley for garnish (optional)',
        ],
        instructions: [
            '-In a large bowl, combine the chicken, soy sauce, and half of the minced garlic. Mix well and marinate for at least 30 minutes, or preferably overnight in the refrigerator.',
            '-Heat the cooking oil in a large pot or deep pan over medium heat. Add the remaining garlic and chopped onion. Sauté until the onion is translucent and the garlic is fragrant.',
            '-Add the marinated chicken (including the marinade) to the pot. Brown the chicken pieces on all sides for about 5-7 minutes.',
            '-Pour in the vinegar, add the bay leaves, whole black peppercorns, and ground black pepper. Allow the mixture to come to a boil without stirring to cook off the strong vinegar taste.',
            '-Once boiling, reduce the heat to low and add water or chicken broth. Cover the pot and let the chicken simmer for about 30 minutes or until tender. Stir occasionally, adding more water if needed.',
            '-If adding potatoes, add them to the pot in the last 15-20 minutes of cooking. Cook until the potatoes are tender.',
            '-If you like hard-boiled eggs in your adobo, add them in the last 5 minutes of cooking to absorb some of the flavors.',
            '-Add brown sugar if you prefer a slightly sweeter adobo. Adjust salt and pepper to taste.',
            '-If you prefer a thicker sauce, remove the lid and let the adobo simmer until the sauce reduces to your desired consistency.',
            '-Serve hot with steamed rice. Garnish with chopped green onions or parsley if desired.',
        ]
    },
    'Adobong Baboy (Pork Adobo)': {
        ingredients: [
            '1 kg (2.2 lbs) pork belly or pork shoulder (cut into cubes)',
            '1/2 cup soy sauce',
            '1/4 cup vinegar',
            '1 medium onion (chopped)',
            '5-6 cloves garlic (minced)',
            '2-3 bay leaves',
            '1/2 teaspoon ground black pepper',
            '1 tablespoon brown sugar (optional)',
            '2 tablespoons cooking oil',
            '1-1.5 cups water or pork broth',
            '2-3 medium potatoes (peeled and quartered, optional)',
            '1 tablespoon cooking oil',
            'Salt to taste',
            'Green onions or parsley for garnish (optional)',
        ],
        instructions: [
            '-In a large bowl, combine the pork with soy sauce and half of the minced garlic. Mix well and marinate for at least 30 minutes, or preferably overnight in the refrigerator.',
            '-Heat the cooking oil in a large pot or deep pan over medium heat. Add the remaining garlic and chopped onion, and sauté until the onion is soft and translucent.',
            '-Add the marinated pork (including the marinade) to the pot. Cook for about 5-7 minutes, turning occasionally, until the pork is browned on all sides.',
            '-Pour in the vinegar, add the bay leaves, whole black peppercorns, and ground black pepper. Allow the mixture to come to a boil without stirring to cook off the strong vinegar taste.',
            '-Once boiling, reduce the heat to low and add water or pork broth. Cover the pot and let the pork simmer for about 45 minutes to 1 hour, or until the meat is tender. Stir occasionally, adding more water if necessary.',
            '-If using potatoes, add them to the pot in the last 15-20 minutes of cooking. Cook until the potatoes are tender.',
            '-Add brown sugar if you prefer a slightly sweeter adobo. Adjust salt and pepper to taste.',
            '-If you prefer a thicker sauce, remove the lid and let the adobo simmer until the sauce reduces to your desired consistency.',
            '-Serve hot with steamed rice. Garnish with chopped green onions or parsley if desired.',
        ]
    },
    'Adobong Pusit (Squid Adobo)': {
        ingredients: [
            '1 kg (2.2 lbs) squid (cleaned and cut into rings, including the tentacles)',
            '1 medium onion (chopped)',
            '5 cloves garlic (minced)',
            '2 tablespoons ginger (sliced into thin strips)',
            '2 tablespoons cooking oil',
            '1/4 cup soy sauce',
            '1/4 cup vinegar',
            '1 teaspoon sugar (optional)',
            '1/4 teaspoon black pepper (ground)',
            '2-3 bay leaves',
            '1-2 pieces green chili or red chili (optional, for spice)',
            'Salt to taste',
            'Water as needed',
            'Green onions or parsley (for garnish, optional)',
        ],
        instructions: [
            '-Clean the squid by removing the ink sac, beak, and innards. Rinse well under cold water. Cut the body into rings and leave the tentacles whole.',
            '-Heat the cooking oil in a pan over medium heat. Sauté the garlic, onion, and ginger until fragrant and the onion is translucent.',
            '-Add the squid to the pan and sauté for about 2-3 minutes until it starts to turn opaque.',
            '-Pour in the soy sauce, vinegar, and a small amount of water (about 1/4 cup). Add the bay leaves, black pepper, and chili (if using). Stir to combine.',
            '-Bring the mixture to a boil, then reduce the heat and let it simmer for about 10-15 minutes. Avoid overcooking the squid to prevent it from becoming tough and rubbery.',
            '-Add sugar if you prefer a slightly sweet contrast to the tangy and salty flavors. Adjust salt and pepper to taste.',
            'Once the squid is tender and the sauce has reduced to your liking, remove the bay leaves. Garnish with green onions or parsley if desired.',
            'Serve hot over steamed rice.'
        ]
    },
    'Adobong Baka (Beef Adobo)':{
        ingredients: [
            '1 kg (2.2 lbs) beef (cut into cubes, preferably chuck or brisket)',
            '1/2 cup soy sauce',
            '1/3 cup vinegar',
            '1 medium onion (chopped)',
            '6 cloves garlic (minced)',
            '2-3 bay leaves',
            '1 teaspoon black peppercorns (whole)',
            '1/2 teaspoon ground black pepper',
            '1 tablespoon brown sugar (optional)',
            '2 tablespoons cooking oil',
            '1-2 cups water or beef broth (adjust for desired sauce consistency)',
            '2 medium potatoes (peeled and quartered, optional)',
            '1 medium carrot (peeled and sliced, optional)',
            'Salt to taste',
        ],
        instructions: [
            '-In a large bowl, combine the beef, soy sauce, and half of the minced garlic. Marinate for at least 30 minutes, or ideally overnight in the refrigerator.',
            '-Heat the cooking oil in a large pot or deep pan over medium heat. Add the remaining garlic and chopped onions, and sauté until the onions are soft and the garlic is fragrant.',
            '-Add the marinated beef (including the marinade) to the pot and brown the meat on all sides. This step helps develop flavor.',
            '-Pour in the vinegar, add the bay leaves, black peppercorns, and ground black pepper. Let the mixture come to a boil without stirring to cook off the strong vinegar taste.',
            '-Once boiling, reduce the heat to low and add water or beef broth, enough to cover the beef. Cover the pot and let it simmer for 1.5 to 2 hours, or until the beef is tender. Stir occasionally and add more water if necessary.',
            '-If using potatoes and carrots, add them to the pot in the last 20-30 minutes of cooking. Cook until the vegetables are tender.',
            '-Add brown sugar if you prefer a hint of sweetness to balance the savory and tangy flavors. Adjust salt and pepper to taste.',
            '-Once the beef is tender and the vegetables are cooked, remove the lid and let the sauce reduce to your desired consistency. You can keep it saucy or let it thicken more, depending on your preference.',
            '-Serve hot over steamed rice, and enjoy your Adobong Baka!',
        ]
    },
    'Adobong Kangkong (Water Spinach Adobo)': {
        ingredients: [
            '2 bunches kangkong (water spinach), cleaned and cut into 3-4 inch lengths (including stalks and leaves)',
            '4 cloves garlic, minced',
            '1 medium onion, chopped',
            '1/4 cup soy sauce',
            '2 tablespoons vinegar',
            '1/4 teaspoon ground black pepper',
            '1-2 bay leaves',
            '1 tablespoon cooking oil',
            '1/4 cup water (optional)',
            '1 teaspoon sugar (optional, for balance)',
            'Salt to taste',
        ],
        instructions: [
            '-Rinse the kangkong thoroughly under cold water to remove any dirt. Cut into 3-4 inch lengths, separating the stalks from the leaves as they have different cooking times.',
            '-Heat the cooking oil in a pan over medium heat. Sauté the garlic and onion until the onion becomes soft and the garlic is fragrant.',
            '-Pour in the soy sauce and vinegar, then add the bay leaves and ground black pepper. Let the mixture simmer for 1-2 minutes without stirring to cook off the sharp vinegar taste.',
            '-Add the kangkong stalks to the pan first since they take a bit longer to cook. Stir to coat them in the sauce and cook for about 2-3 minutes until they start to soften.',
            '-Once the stalks are slightly tender, add the kangkong leaves. Stir everything together and cook for another 1-2 minutes, or until the leaves are wilted.',
            '-If you prefer a slightly sweeter adobo, you can add sugar at this point. Adjust salt and pepper to taste.',
            '-If you want more sauce, add a small amount of water and let it simmer for an additional minute.',
            '-Remove from heat and serve immediately. Adobong Kangkong is best enjoyed with steamed rice.',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
    '':{
        ingredients: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ],
        instructions: [
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ]
    },
};

function showPopupCard(recipeName) {
    const recipe = recipes[recipeName];
    if (recipe) {
        const popupText = `
            <h2>This is ${recipeName} recipe</h2>
            <h3>Ingredients</h3>
            <ul class="ingredients-list">
                ${recipe.ingredients.map(ingredient => `<li>${ingredient}</li>`).join('')}
            </ul>
            <h3>Instructions</h3>
            <ol class="instructions-list">
                ${recipe.instructions.map(instruction => `<li>${instruction}</li>`).join('')}
            </ol>
        `;
        document.getElementById('popup-text').innerHTML = popupText;
        document.getElementById('popup-card').style.display = 'flex';
    }
}

function closePopupCard() {
    document.getElementById('popup-card').style.display = 'none';
}

